name: Flask CI with Docker

on:
  push:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest

  test-docker:
    runs-on: ubuntu-latest
    needs: test  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and run container
        run: |
          docker build -t flask-ci-demo:test .
          docker run -d -p 5000:5000 --name flask-test flask-ci-demo:test
          sleep 5  # подождать запуск
          curl -f http://localhost:5000/ || (docker logs flask-test && exit 1)
          docker stop flask-test
          docker rm flask-test

  build-docker:
    runs-on: ubuntu-latest
    needs: test-docker  # финальный билд образа

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t flask-ci-demo:latest .
