name: CD to VDS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VDS
    runs-on: ubuntu-latest

    steps:
      - name: Connect to VDS and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.VDS_KEY }}
          script: |
            echo "[+] Deploying flask-ci-demo to VDS"
            cd /home/flask-ci-demo
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart flaskapp
            echo "[+] Done. App restarted"
